env = GTK_THEME,catppuccin-mocha-mauve-standard+default:dark

bindl = SUPER, L, exec, hyprlock

bindl = , switch:on:Lid Switch,  exec, ~/.config/hypr/bin/lidclosed.sh
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "e-DP-1, enable" & hyprctl reload

windowrule = match:class ^kitty$, size 1750 580
