listener {
    timeout = 300

    on-timeout = hyprdvd -s
    on-resume = pkill -9 hyprdvd
}

listener {
    timeout = 600

    on-timeout = pkill -9 hyprdvd; hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on; pidof waybar || waybar
}
